package ntut.csie.backlogItemImportanceService.useCase.backlogItemImportance.get;

import ntut.csie.backlogItemImportanceService.useCase.UseCase;

public interface GetBacklogItemImportanceByBacklogItemIdUseCase extends UseCase<GetBacklogItemImportanceByBacklogItemIdInput, GetBacklogItemImportanceByBacklogItemIdOutput> {

}
